import Head from "next/head";
import Image from "next/image";
import { GithubService } from "@/services/GithubServices";
import { useEffect, useState } from "react";
import TopHeader from "@/components/Navbar/TopHeader";
import GithubIcon from "../../public/icons/github.svg";

export default function Home() {
  const githubService = new GithubService();
  const [user, setUser] = useState<any>();

  useEffect(() => {
    async function fetchUserData() {
      const data = (await githubService.getUserData()).data;
      setUser(data);
      console.log(data);
    }

    fetchUserData();
  }, []);
  return (
    <>
      <Head>
        <title>Git Viewer | Ananda Zukhruf</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TopHeader
          content={
            <>
              <Image src={GithubIcon.src} alt="icon" width={42} height={42} />
              <h1>Github Viewer</h1>
            </>
          }
        />
        <div className="content">
          <div className="profile-container">
            <div className="image-container">
              <img src={user?.avatar_url} />
            </div>
            <div className="text-container">
              <h1>{user?.name}</h1>
              <h3>{user?.login}</h3>
              <p>{user?.bio}</p>
            </div>
          </div>
          <div className="repo-container">

          </div>
        </div>
      </main>
    </>
  );
}
